version: '3.4'

services:
  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:3-management-alpine

  redis:
    container_name: RedisData
    image: redis:latest

  mssqldb:
    container_name: MssqlDB
    image: mcr.microsoft.com/mssql/server:2022-latest
        
  identityserver:
    container_name: IdentityServer
    build:
      context: ..
      dockerfile: ./src/IdentityServer/OpenIddictAPI/Dockerfile    
    depends_on:
      - mssqldb

  gateway-api:
    container_name: gateway-api
    build:
      context: ..
      dockerfile: ./src/GatewayApi/Dockerfile

  # product:
  #   container_name: product
  #   build:
  #     context: ..
  #     dockerfile: ./src/ProductAPI/Dockerfile
  #   depends_on:
  #     - sqlserver

  # order:
  #   container_name: order
  #   build:
  #     context: ..
  #     dockerfile: ./src/OrderAPI/Dockerfile
  #   depends_on:
  #     - sqlserver
  