version: '3.8'

services:
  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  redis:
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  # redis_insight:    
  #     ports:
  #       - 8001:8001
  #     volumes:
  #       - redis_insight_data:/db

  # mssqldb:
  #   ports:
  #     - 1433:1433
  #   environment:
  #     ACCEPT_EULA: 'Y'
  #     MSSQL_SA_PASSWORD: 'sqladmin123!@#'
  #     MSSQL_DATA_DIR: /var/opt/mssql/data
  #     MSSQL_PID: 'Developer' 
  #     MSSQL_TCP_PORT: 1433 
  #   volumes:
  #     - ./data:/var/opt/mssql/data
  #     - ./log:/var/opt/mssql/log
  #     - ./secrets:/var/opt/mssql/secrets

  # gateway-api:
  #   ports:
  #     - 5000:8080
  #     - 5001:8081
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=docker
  #     - ASPNETCORE_HTTP_PORTS=8080

  # identityserver:
  #   ports:
  #     - 5180:8080
  #     - 5181:8081
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=docker
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - ConnectionStrings=Server=mssqldb;Database=IdentityServerDB;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true;Encrypt=False



# volumes:
#   redis_data:
#   redis_insight_data:
  



  # product:
  #   ports:
  #     - "8001:8080" 
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080

  # order:
  #   ports:
  #     - "8002:8080"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  
