@OpenIddictAPI_HostAddress = http://localhost:5008

POST {{OpenIddictAPI_HostAddress}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=admin&password=Admin@123&client_id=WebApiCC&client_secret=YTOGh5kJBBEbiPXLUBNpZdrOMQmjBSVc

###
